name: Question
description: Ask about something here.
labels: [question]
body:
  - type: textarea
    attributes:
      label: What is your question? (Please check for duplicates or similar issues before creating this issue.)
    validations:
      required: true